export const DEFAULT_MENU_FONT = 'Plus Jakarta Sans'
export const DEFAULT_MENU_BACKGROUND_COLOR = '#F4F2EE'

export const FONT_OPTIONS = [
    { label: 'Plus Jakarta Sans', value: 'Plus Jakarta Sans' },
    { label: 'Fjalla One', value: 'Fjalla One' },
    { label: 'Georgia', value: 'Georgia' },
    { label: 'Times New Roman', value: 'Times New Roman' },
    { label: 'Arial', value: 'Arial' },
    { label: 'Courier New', value: 'Courier New' },
    // Google Fonts
    { label: 'Inter', value: 'Inter' },
    { label: 'Roboto', value: 'Roboto' },
    { label: 'Open Sans', value: 'Open Sans' },
    { label: 'Lato', value: 'Lato' },
    { label: 'Montserrat', value: 'Montserrat' },
    { label: 'Oswald', value: 'Oswald' },
    { label: 'Raleway', value: 'Raleway' },
    { label: 'Merriweather', value: 'Merriweather' },
    { label: 'Playfair Display', value: 'Playfair Display' },
    { label: 'Lora', value: 'Lora' },
    { label: 'Nunito', value: 'Nunito' },
    { label: 'Poppins', value: 'Poppins' },
    { label: 'Ubuntu', value: 'Ubuntu' },
    { label: 'Dancing Script', value: 'Dancing Script' },
    { label: 'Pacifico', value: 'Pacifico' },
    { label: 'Abril Fatface', value: 'Abril Fatface' },
    { label: 'Bebas Neue', value: 'Bebas Neue' },
    { label: 'Lobster', value: 'Lobster' },
    { label: 'Comfortaa', value: 'Comfortaa' },
]

export const FONT_FAMILY_MAP: Record<string, string> = {
    'Plus Jakarta Sans': 'var(--font-plus-jakarta-sans), sans-serif',
    'Fjalla One': 'var(--font-fjalla-one), sans-serif',
    'Georgia': 'Georgia, serif',
    'Times New Roman': '"Times New Roman", serif',
    'Arial': 'Arial, sans-serif',
    'Courier New': '"Courier New", monospace',
    // Google Fonts mappings
    'Inter': 'var(--font-inter), sans-serif',
    'Roboto': 'var(--font-roboto), sans-serif',
    'Open Sans': 'var(--font-open-sans), sans-serif',
    'Lato': 'var(--font-lato), sans-serif',
    'Montserrat': 'var(--font-montserrat), sans-serif',
    'Oswald': 'var(--font-oswald), sans-serif',
    'Raleway': 'var(--font-raleway), sans-serif',
    'Merriweather': 'var(--font-merriweather), serif',
    'Playfair Display': 'var(--font-playfair-display), serif',
    'Lora': 'var(--font-lora), serif',
    'Nunito': 'var(--font-nunito), sans-serif',
    'Poppins': 'var(--font-poppins), sans-serif',
    'Ubuntu': 'var(--font-ubuntu), sans-serif',
    'Dancing Script': 'var(--font-dancing-script), cursive',
    'Pacifico': 'var(--font-pacifico), cursive',
    'Abril Fatface': 'var(--font-abril-fatface), display',
    'Bebas Neue': 'var(--font-bebas-neue), sans-serif',
    'Lobster': 'var(--font-lobster), display',
    'Comfortaa': 'var(--font-comfortaa), cursive',
}
